apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jrcwh5331-nodejs
  janus-idp.io/tekton: jrcwh5331-nodejs
  backstage.io/kubernetes-id: jrcwh5331-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jrcwh5331-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
