apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jrcwh5331-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jrcwh5331-nodejs 
  name: jrcwh5331-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jrcwh5331-nodejs 
